import { useState } from 'react';
import { useAppStore } from '@/store';
import { useI18n } from '@/lib/i18n';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { AlertCircle, CheckCircle2, UserPlus, UserMinus } from 'lucide-react';

// Composant Input numérique qui permet d'effacer et réécrire
function NumericInput({ 
  id, 
  value, 
  onChange, 
  min, 
  max, 
  defaultValue 
}: { 
  id: string; 
  value: number; 
  onChange: (value: number) => void; 
  min: number; 
  max: number; 
  defaultValue: number;
}) {
  const [localValue, setLocalValue] = useState(String(value));
  const [isFocused, setIsFocused] = useState(false);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setLocalValue(e.target.value);
  };

  const handleBlur = () => {
    setIsFocused(false);
    const parsed = parseInt(localValue);
    if (isNaN(parsed) || parsed < min) {
      setLocalValue(String(defaultValue));
      onChange(defaultValue);
    } else if (parsed > max) {
      setLocalValue(String(max));
      onChange(max);
    } else {
      setLocalValue(String(parsed));
      onChange(parsed);
    }
  };

  const handleFocus = () => {
    setIsFocused(true);
  };

  // Sync avec la valeur externe si on n'est pas en train d'éditer
  if (!isFocused && String(value) !== localValue) {
    setLocalValue(String(value));
  }

  return (
    <Input
      id={id}
      type="number"
      min={min}
      max={max}
      value={localValue}
      onChange={handleChange}
      onBlur={handleBlur}
      onFocus={handleFocus}
    />
  );
}

export function ConfigurationPanel() {
  const { configuration, updateConfiguration, guests, autoCompleteGuests, removeExcessAutoGeneratedGuests } = useAppStore();
  const { t, locale } = useI18n();

  // Calcul des capacités
  const totalCapacity = configuration.honorTableSeats + (configuration.numberOfTables * configuration.seatsPerTable);
  const missingGuests = configuration.totalGuests - guests.length;
  const capacityDiff = totalCapacity - configuration.totalGuests;
  
  // Invités en trop par rapport à la capacité
  const excessGuestsCapacity = guests.length - totalCapacity;
  const hasExcessGuestsCapacity = excessGuestsCapacity > 0;
  
  // Invités en trop par rapport au nombre total configuré
  const excessGuestsTotal = guests.length - configuration.totalGuests;
  const hasExcessGuestsTotal = excessGuestsTotal > 0;
  
  // Nombre d'invités auto-générés
  const autoGeneratedCount = guests.filter(g => g.firstName.startsWith('Invité')).length;
  const realGuestsCount = guests.length - autoGeneratedCount;
  
  // Pour la capacité
  const canRemoveAutoGeneratedCapacity = autoGeneratedCount > 0 && excessGuestsCapacity > 0;
  const autoGeneratedToRemoveCapacity = Math.min(autoGeneratedCount, excessGuestsCapacity);
  
  // Pour le nombre total configuré
  const canRemoveAutoGeneratedTotal = autoGeneratedCount > 0 && excessGuestsTotal > 0;
  const autoGeneratedToRemoveTotal = Math.min(autoGeneratedCount, excessGuestsTotal);
  const hasOnlyRealGuestsExcess = excessGuestsTotal > 0 && autoGeneratedCount === 0;

  // Messages de validation
  const hasCapacityIssue = capacityDiff < 0;
  const hasExtraCapacity = capacityDiff > 0;
  const hasMissingGuests = missingGuests > 0;

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-lg">⚙️ {t('configTitle')}</CardTitle>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Nombre de places */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <div className="space-y-2">
            <Label htmlFor="totalGuests">{t('totalGuests')}</Label>
            <NumericInput
              id="totalGuests"
              min={1}
              max={200}
              defaultValue={50}
              value={configuration.totalGuests}
              onChange={(value) => updateConfiguration({ totalGuests: value })}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="numberOfTables">{t('numberOfTables')}</Label>
            <NumericInput
              id="numberOfTables"
              min={1}
              max={30}
              defaultValue={6}
              value={configuration.numberOfTables}
              onChange={(value) => updateConfiguration({ numberOfTables: value })}
            />
            <p className="text-xs text-muted-foreground">
              {locale === 'fr' ? "Hors table d'honneur" : "Excluding honor table"}
            </p>
          </div>
          <div className="space-y-2">
            <Label htmlFor="seatsPerTable">{t('seatsPerTable')}</Label>
            <NumericInput
              id="seatsPerTable"
              min={2}
              max={20}
              defaultValue={8}
              value={configuration.seatsPerTable}
              onChange={(value) => updateConfiguration({ seatsPerTable: value })}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="honorTableSeats">{t('honorTableSeats')}</Label>
            <NumericInput
              id="honorTableSeats"
              min={2}
              max={30}
              defaultValue={10}
              value={configuration.honorTableSeats}
              onChange={(value) => updateConfiguration({ honorTableSeats: value })}
            />
          </div>
        </div>

        {/* Résumé des capacités */}
        <div className="bg-muted/50 p-4 rounded-lg space-y-2">
          <div className="flex justify-between text-sm">
            <span>{locale === 'fr' ? "Table d'honneur :" : "Honor table:"}</span>
            <span className="font-medium">{configuration.honorTableSeats} {locale === 'fr' ? 'places' : 'seats'}</span>
          </div>
          <div className="flex justify-between text-sm">
            <span>{configuration.numberOfTables} {locale === 'fr' ? 'tables' : 'tables'} × {configuration.seatsPerTable} {locale === 'fr' ? 'places' : 'seats'}:</span>
            <span className="font-medium">{configuration.numberOfTables * configuration.seatsPerTable} {locale === 'fr' ? 'places' : 'seats'}</span>
          </div>
          <div className="border-t pt-2 flex justify-between font-semibold">
            <span>{locale === 'fr' ? 'Capacité totale :' : 'Total capacity:'}</span>
            <span className={hasCapacityIssue ? 'text-destructive' : 'text-green-600'}>
              {totalCapacity} {locale === 'fr' ? 'places' : 'seats'}
            </span>
          </div>
        </div>

        {/* Messages d'alerte */}
        {hasCapacityIssue && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              <strong>{t('insufficientCapacity')}</strong> {locale === 'fr' 
                ? `Il manque ${Math.abs(capacityDiff)} place(s) pour accueillir tous les invités.`
                : `${Math.abs(capacityDiff)} seat(s) missing to accommodate all guests.`}
            </AlertDescription>
          </Alert>
        )}

        {hasExtraCapacity && !hasCapacityIssue && (
          <Alert variant="default" className="border-blue-200 bg-blue-50">
            <CheckCircle2 className="h-4 w-4 text-blue-600" />
            <AlertDescription className="text-blue-800">
              <strong>{t('capacityOk')}:</strong> {locale === 'fr'
                ? `Vous avez ${capacityDiff} place(s) supplémentaire(s) disponible(s).`
                : `You have ${capacityDiff} extra seat(s) available.`}
            </AlertDescription>
          </Alert>
        )}

        {hasMissingGuests && (
          <Alert variant="warning">
            <AlertDescription className="flex items-center justify-between">
              <span>
                <strong>{missingGuests} {locale === 'fr' ? 'invité(s) non renseigné(s)' : 'guest(s) not entered'}</strong> {locale === 'fr' ? `sur ${configuration.totalGuests} prévus.` : `of ${configuration.totalGuests} expected.`}
              </span>
              <Button 
                size="sm" 
                variant="outline" 
                onClick={autoCompleteGuests}
                className="ml-4"
              >
                <UserPlus className="h-4 w-4 mr-2" />
                {t('autoComplete')}
              </Button>
            </AlertDescription>
          </Alert>
        )}

        {!hasMissingGuests && !hasExcessGuestsTotal && guests.length > 0 && !hasExcessGuestsCapacity && (
          <Alert variant="default" className="border-green-200 bg-green-50">
            <CheckCircle2 className="h-4 w-4 text-green-600" />
            <AlertDescription className="text-green-800">
              <strong>{locale === 'fr' ? 'Liste complète :' : 'Complete list:'}</strong> {locale === 'fr' 
                ? `Tous les ${guests.length} invités sont renseignés.`
                : `All ${guests.length} guests are entered.`}
            </AlertDescription>
          </Alert>
        )}

        {/* Alerte si trop d'invités par rapport au nombre total configuré */}
        {hasExcessGuestsTotal && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription className="flex items-center justify-between">
              <span>
                <strong>{locale === 'fr' ? 'Invités en excès :' : 'Excess guests:'}</strong>{' '}
                {locale === 'fr' 
                  ? `${excessGuestsTotal} invité(s) en trop par rapport au nombre configuré (${guests.length}/${configuration.totalGuests}).`
                  : `${excessGuestsTotal} guest(s) exceed configured total (${guests.length}/${configuration.totalGuests}).`}
              </span>
              {canRemoveAutoGeneratedTotal ? (
                <Button 
                  size="sm" 
                  variant="outline" 
                  onClick={() => removeExcessAutoGeneratedGuests(autoGeneratedToRemoveTotal)}
                  className="ml-4 border-destructive text-destructive hover:bg-destructive hover:text-destructive-foreground"
                >
                  <UserMinus className="h-4 w-4 mr-2" />
                  {locale === 'fr' 
                    ? `Supprimer ${autoGeneratedToRemoveTotal} invité(s) généré(s)`
                    : `Remove ${autoGeneratedToRemoveTotal} generated guest(s)`}
                </Button>
              ) : hasOnlyRealGuestsExcess ? (
                <span className="text-xs ml-4">
                  {locale === 'fr' 
                    ? 'Augmentez le nombre total ou supprimez des invités manuellement'
                    : 'Increase total count or remove guests manually'}
                </span>
              ) : null}
            </AlertDescription>
          </Alert>
        )}

        {/* Alerte si trop d'invités par rapport à la capacité */}
        {hasExcessGuestsCapacity && !hasExcessGuestsTotal && (
          <Alert variant="destructive">
            <AlertCircle className="h-4 w-4" />
            <AlertDescription className="flex items-center justify-between">
              <span>
                <strong>{locale === 'fr' ? 'Capacité insuffisante :' : 'Insufficient capacity:'}</strong>{' '}
                {locale === 'fr' 
                  ? `${excessGuestsCapacity} invité(s) en trop par rapport à la capacité des tables (${guests.length}/${totalCapacity}).`
                  : `${excessGuestsCapacity} guest(s) exceed table capacity (${guests.length}/${totalCapacity}).`}
              </span>
              {canRemoveAutoGeneratedCapacity && (
                <Button 
                  size="sm" 
                  variant="outline" 
                  onClick={() => removeExcessAutoGeneratedGuests(autoGeneratedToRemoveCapacity)}
                  className="ml-4 border-destructive text-destructive hover:bg-destructive hover:text-destructive-foreground"
                >
                  <UserMinus className="h-4 w-4 mr-2" />
                  {locale === 'fr' 
                    ? `Supprimer ${autoGeneratedToRemoveCapacity} invité(s) généré(s)`
                    : `Remove ${autoGeneratedToRemoveCapacity} generated guest(s)`}
                </Button>
              )}
            </AlertDescription>
          </Alert>
        )}

        {/* Critères de tri */}
        <div className="space-y-3">
          <Label className="text-base font-semibold">{t('sortingCriteria')}</Label>
          <p className="text-sm text-muted-foreground">
            {locale === 'fr' 
              ? 'Sélectionnez les critères pour organiser le placement'
              : 'Select criteria to organize placement'}
          </p>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="flex items-center space-x-2">
              <Checkbox
                id="byRole"
                checked={configuration.sortingCriteria.byRole}
                onCheckedChange={(checked) =>
                  updateConfiguration({
                    sortingCriteria: {
                      ...configuration.sortingCriteria,
                      byRole: !!checked,
                    },
                  })
                }
              />
              <Label htmlFor="byRole" className="cursor-pointer">
                {t('byRole')}
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="byFamily"
                checked={configuration.sortingCriteria.byFamily}
                onCheckedChange={(checked) =>
                  updateConfiguration({
                    sortingCriteria: {
                      ...configuration.sortingCriteria,
                      byFamily: !!checked,
                    },
                  })
                }
              />
              <Label htmlFor="byFamily" className="cursor-pointer">
                {t('byFamily')}
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="byAge"
                checked={configuration.sortingCriteria.byAge}
                onCheckedChange={(checked) =>
                  updateConfiguration({
                    sortingCriteria: {
                      ...configuration.sortingCriteria,
                      byAge: !!checked,
                    },
                  })
                }
              />
              <Label htmlFor="byAge" className="cursor-pointer">
                {t('byAge')}
              </Label>
            </div>
            <div className="flex items-center space-x-2">
              <Checkbox
                id="random"
                checked={configuration.sortingCriteria.random}
                onCheckedChange={(checked) =>
                  updateConfiguration({
                    sortingCriteria: {
                      ...configuration.sortingCriteria,
                      random: !!checked,
                    },
                  })
                }
              />
              <Label htmlFor="random" className="cursor-pointer">
                {t('random')}
              </Label>
            </div>
          </div>
        </div>

        {/* Info sur les champs dynamiques */}
        <div className="text-sm text-muted-foreground bg-muted p-3 rounded-md">
          <strong>{locale === 'fr' ? 'Champs activés :' : 'Enabled fields:'}</strong>
          <ul className="list-disc list-inside mt-1">
            {configuration.sortingCriteria.byFamily && (
              <li>{locale === 'fr' ? 'Nom de famille (pour regrouper par famille)' : 'Last name (to group by family)'}</li>
            )}
            {configuration.sortingCriteria.byAge && (
              <li>{locale === 'fr' ? 'Âge (pour regrouper par tranche d\'âge)' : 'Age (to group by age range)'}</li>
            )}
            {configuration.sortingCriteria.byRole && (
              <li>{locale === 'fr' ? 'Rôle (Marié/Témoin pour la table d\'honneur)' : 'Role (Married/Witness for honor table)'}</li>
            )}
          </ul>
        </div>
      </CardContent>
    </Card>
  );
}
