// ============================================
// CORE TYPES - Guest Management
// ============================================

/**
 * Special role for a guest (for the honor table)
 */
export type GuestRole = 'married' | 'witness' | 'bridesmaid' | 'groomsman' | 'regular';

/**
 * Individual guest with all attributes
 */
export interface Guest {
  id: string;
  firstName: string;
  lastName?: string | undefined; // Enabled if "By Family" criteria is active
  age?: number | undefined; // Enabled if "By Age" criteria is active
  role: GuestRole; // Enabled if "By Role" criteria is active
  coupleId?: string | undefined; // Reference to couple if guest is part of one
}

/**
 * Couple (two guests who must be together)
 */
export interface Couple {
  id: string;
  guestAId: string;
  guestBId: string;
}

// ============================================
// CONSTRAINTS
// ============================================

/**
 * Exclusion constraint: two guests cannot be at the same table
 */
export interface ExclusionConstraint {
  id: string;
  guestAId: string;
  guestBId: string;
}

// ============================================
// CONFIGURATION
// ============================================

/**
 * Sorting criteria selectable by user
 */
export interface SortingCriteria {
  byFamily: boolean;
  byAge: boolean;
  byRole: boolean;
  random: boolean;
}

/**
 * Table shape in visual view
 */
export type TableShape = 'round' | 'square';

/**
 * Global seating plan configuration
 */
export interface PlanConfiguration {
  totalGuests: number;
  numberOfTables: number; // Number of tables (excluding honor table)
  seatsPerTable: number;
  honorTableSeats: number; // Number of seats at the honor table
  sortingCriteria: SortingCriteria;
  tableShape: TableShape;
}

// ============================================
// TABLES & OUTPUT
// ============================================

/**
 * Table with assigned guests
 */
export interface Table {
  id: string;
  number: number; // 1 = honor table
  name: string;
  guests: Guest[];
  capacity: number;
}

/**
 * Warning generated by algorithm (soft constraint not respected)
 */
export interface Warning {
  type: 'exclusion_violated' | 'family_split' | 'age_mismatch';
  message: string;
  guestIds: string[];
}

/**
 * Result of seating plan generation
 */
export interface SeatingPlanResult {
  success: boolean;
  tables: Table[];
  warnings: Warning[];
  errors: string[];
  debugLog?: string | undefined; // Optional debug log
}

// ============================================
// ALGORITHM INPUT
// ============================================

/**
 * Complete input for placement algorithm
 */
export interface AlgorithmInput {
  guests: Guest[];
  couples: Couple[];
  exclusions: ExclusionConstraint[];
  configuration: PlanConfiguration;
}

// ============================================
// STORE STATE
// ============================================

/**
 * Complete application state
 */
export interface AppState {
  // Data
  guests: Guest[];
  couples: Couple[];
  exclusions: ExclusionConstraint[];
  configuration: PlanConfiguration;

  // Generated result
  result: SeatingPlanResult | null;

  // UI State
  viewMode: 'cards' | 'visual';
  isGenerating: boolean;
}

// ============================================
// UTILITY TYPES
// ============================================

/**
 * Type for positions in visual table view
 */
export interface TablePosition {
  tableId: string;
  x: number;
  y: number;
}

/**
 * Type for CSV export
 */
export interface CSVRow {
  tableNumber: number;
  tableName: string;
  guestName: string;
  role: string;
  family?: string;
}
